### PR TITLE
remove binaries & output, add to gitignore

### PR DESCRIPTION
**Pull request by ihaveamac**
you should be adding some things like makerom to your path. binaries should not be placed in the repository.

### CODE REVIEW

**Comment by Manurocker95** [comment]
I tried but my W10 seems to refuse to compile that way :/

**Comment by ihaveamac** [comment]
tried what?

**Comment by Manurocker95** [comment]
yup _:/

**Comment by ihaveamac** [comment]
that doesn't answer the question.

**Comment by Manurocker95** [comment]
Placed the makerom to the makefile and stuff

**Comment by ihaveamac** [comment]
put makerom in your path and it should work fine. or at the very least stop pushing it to the repo (this is why .gitignore exists).

**Comment by Dude1452** [comment]
Doesn't makerom go in "path to devkitARM"/bin?

**Pull request closed without merging**
